services:
  advent-of-code-downloader:
    container_name: advent-of-code
    build: .
    entrypoint: ['python', '-m', 'infrastructure.utils.downloader', '--year=$YEAR', '--day=$DAY']
    env_file:
      - .env
    volumes:
      - ./inputs:/app/inputs

  advent-of-code-runner:
    container_name: advent-of-code-runner
    build: .
    entrypoint: ['python', '-m', 'solutions.year_$YEAR.day_$DAY.part_${PART}']
    env_file:
      - .env
    volumes:
      - ./inputs:/app/inputs
    depends_on:
      - advent-of-code-downloader
